### ISSUE TITLE
Write vignette

### ISSUE THREAD

**Issue by ateucher** [bcgov/rcaaqs#1]
Write a vignette showing basic use of the package

**Comment by daattali** [comment]
@ateucher @stephhazlitt even without a vignette, I think it'd be useful to have in the README just an example of how to load data into one of the main functions. I just looked at all the `pm_*` functions, and I saw the included `airzone_map`, but I couldn't figure out how to run any of the functions because I don't know where the sample dataframe is

**Comment by ateucher** [comment]
Great idea, thanks @daattali.  I'll load something up into the README today.

**Comment by ateucher** [comment]
I've updated the README with a simple example of the core functionality for PM<sub>2.5</sub>

**Comment by daattali** [comment]
That's extremely useful, thanks. I noticed in the joined `ann_98_per`, the `n_days.x` and `n_days.y` are not identical.  I'm assuming that's expected because of different ways the two methods filter the days, but just wanted to bring it up in case it's not expected

**Comment by ateucher** [comment]
Thanks for pointing that out @daattali. I'll look at it after we assign #14.

**Comment by ateucher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation](https://trello.com/c/dO0cFfu9/7-documentation)
